### ISSUE TITLE
Any plans of making a cli tool?

### ISSUE THREAD

**Issue by sheepster1** [maormagori/Ktuvit-api#1]
Cool work!
Do you have any plans of creating a CLI tool or integrating into an existing one like subliminal or even writing a plugin for Jellyfin or Plex?

**Comment by maormagori** [comment]
Hey @sheepster1 ,
Glad to hear you liked it! I originally wrote this package to use it in another tool that I was working on so I had no plans making it a standalone tool or integrate it with other tools. Since the holiday is coming up, making a CLI sounds like a fun project to pick up so I might give it a shot. 
About integrating with other tools...
That's why this is an NPM package, for other developers to use. So if you, or any other developers from these tools, would like to take up the glove you know where the documentation is 😉

**Comment by maormagori** [comment]
Might want to take a look: [screwzira-subtitle-downloader](https://github.com/yoavain/screwzira-subtitle-downloader)

**Comment by TwillightMercy** [comment]
Any plans to make this a Stremio subtitles addon?
